import { z } from "zod";

/**
 * Shared building blocks for canonical models (SDD §11).
 *
 * Draft status (M0): shapes are expected to be refined in M1 when storage
 * round-trips exercise them. Field *removals* after M1 require a migration.
 */

/** Entity/fact identifier. Opaque, unique, non-empty. Generated by callers (storage layer). */
export const IdSchema = z.string().min(1);
export type Id = z.infer<typeof IdSchema>;

/** ISO-8601 timestamp with timezone offset (UTC recommended). */
export const TimestampSchema = z.iso.datetime({ offset: true });
export type Timestamp = z.infer<typeof TimestampSchema>;

/** ISO-8601 calendar date (YYYY-MM-DD), for dates without a meaningful time. */
export const DateOnlySchema = z.iso.date();
export type DateOnly = z.infer<typeof DateOnlySchema>;

/** Every persisted canonical model carries its schema version (SDD §11, §14). */
export const SCHEMA_VERSION = 1;
export const SchemaVersionSchema = z.number().int().positive();

/**
 * How a normalized field/model was extracted from its raw envelope (SDD §9).
 * "structured" = JSON-LD / native API, "dom" = per-source selectors,
 * "ai" = LLM fallback extraction, "user" = entered or edited by the user.
 */
export const ExtractionTierSchema = z.enum(["structured", "dom", "ai", "user"]);
export type ExtractionTier = z.infer<typeof ExtractionTierSchema>;

/**
 * Provenance for anything that entered Hunt via ingestion (SDD §8, §9).
 * Opaque metadata: usable for display and re-normalization, never for
 * branching logic outside the ingestion package.
 */
export const ProvenanceSchema = z.object({
  sourceId: z.string().min(1),
  adapterVersion: z.string().min(1),
  inputRef: z.string().min(1),
  envelopeHash: z.string().min(1),
  extractionTier: ExtractionTierSchema,
  fetchedAt: TimestampSchema,
  normalizedAt: TimestampSchema,
});
export type Provenance = z.infer<typeof ProvenanceSchema>;
